### ISSUE TITLE
No module named new

### ISSUE THREAD

**Issue by JRMN1** [alexer/python-xlib#1]
The new module has been removed in Python 3.  How do I use xlib with python 3?  In Xlib.display there is a import new in the code.  thanks in advance

**Comment by alexer** [comment]
Like the description says, this is an "Unofficial git mirror of the python-xlib subversion repository". That is, this git repository is in no way affiliated with the python-xlib project. You should probably mail the python-xlib's mailing list with your problem instead.

That being said, as far as I know python-xlib doesn't support python3 at all. Even if you fix the problem with the missing new-module, there are likely lots of other incompatibilities with python3, especially since from what I've heard, python-xlib supports python versions down to 1.5.2, which probably means it often has to use older - possibly python3-incompatible - ways of doing things.
